name: Azure Static Web Apps - CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build (if you have a build step)
        run: |
          if [ -f package.json ]; then
            npm ci
            if npm run | grep -q 'build'; then
              npm run build
            fi
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          #### Update the app_location if your site is in a subfolder (default is '/')
          app_location: "/"
          #### If you have a build output folder, set it here. Otherwise leave as root
          output_location: ""
